/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;


public class AddNewUser extends javax.swing.JFrame
{

    /**
     * Creates new form add_new_user
     */
    public AddNewUser()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButton = new javax.swing.ButtonGroup();
        userButton = new javax.swing.ButtonGroup();
        newUserAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonFemale = new javax.swing.JRadioButton();
        buttonMale = new javax.swing.JRadioButton();
        buttonOther = new javax.swing.JRadioButton();
        buttonNotSay = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        pButton = new javax.swing.JButton();
        tfPassword2 = new javax.swing.JPasswordField();
        buttonSupplier = new javax.swing.JRadioButton();
        category = new javax.swing.JLabel();
        buttonCustomer = new javax.swing.JRadioButton();
        buttonPharmacist = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        exitFromAddUser = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        boxBloodGroup = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        boxInsurance = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        boxAge = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newUserAdd.setBackground(new java.awt.Color(204, 204, 204));
        newUserAdd.setFont(new java.awt.Font("Monospaced", 3, 11)); // NOI18N
        newUserAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/add-box-fill.png"))); // NOI18N
        newUserAdd.setText("ADD");
        newUserAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        newUserAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserAddMouseClicked(evt);
            }
        });
        newUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("NAME");

        tfID.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("SURNAME");

        tfSurname.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        tfSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSurnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("USERNAME");

        tfUsername.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Please write password again");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("PASSWORD(MIN LENGTH OF 6)");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("GENDER");

        genderButton.add(buttonFemale);
        buttonFemale.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonFemale.setText("Female");
        buttonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFemaleActionPerformed(evt);
            }
        });

        genderButton.add(buttonMale);
        buttonMale.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonMale.setText("Male");
        buttonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMaleActionPerformed(evt);
            }
        });

        genderButton.add(buttonOther);
        buttonOther.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonOther.setText("Other");

        genderButton.add(buttonNotSay);
        buttonNotSay.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonNotSay.setText("Rather not say");

        jLabel11.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel11.setText("ID");

        tfName.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPasswordKeyTyped(evt);
            }
        });

        pButton.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton.setText("Show");
        pButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButtonMouseReleased(evt);
            }
        });

        tfPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPassword2KeyTyped(evt);
            }
        });

        userButton.add(buttonSupplier);
        buttonSupplier.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonSupplier.setText("Supplier");
        buttonSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSupplierMouseClicked(evt);
            }
        });
        buttonSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSupplierActionPerformed(evt);
            }
        });

        category.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        category.setText("First, please select membership type:");

        userButton.add(buttonCustomer);
        buttonCustomer.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonCustomer.setText("Customer");
        buttonCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCustomerMouseClicked(evt);
            }
        });

        userButton.add(buttonPharmacist);
        buttonPharmacist.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonPharmacist.setText("Pharmacist");
        buttonPharmacist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPharmacistMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/user-2-line-adduser.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonPharmacist)
                                    .addComponent(buttonCustomer)
                                    .addComponent(buttonSupplier))
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonNotSay)
                                    .addComponent(buttonOther)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfPassword2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfSurname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfName, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(223, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(category)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPharmacist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFemale)
                    .addComponent(buttonOther))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMale)
                    .addComponent(buttonNotSay)))
        );

        exitFromAddUser.setBackground(new java.awt.Color(204, 204, 204));
        exitFromAddUser.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        exitFromAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/close-fill-adduser.png"))); // NOI18N
        exitFromAddUser.setText("EXIT");
        exitFromAddUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        exitFromAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitFromAddUserMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setText("INSURANCE");

        boxBloodGroup.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        boxBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A RhD positive (A+)", "A RhD negative (A-)", "B RhD positive (B+)", "B RhD negative (B-)", "O RhD positive (O+)", "O RhD negative (O-)", "AB RhD positive (AB+)", "AB RhD negative (AB-)" }));
        boxBloodGroup.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setText("BLOOD GROUP");

        boxInsurance.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        boxInsurance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "SGK", "Emekli Sandığı", "Ace Grup Sigorta", "Acıbadem", "Akbank", "Allianz Sigorta", "Anadolu Sigorta", "Benefit Global&Euroko Sigorta", "Demir Hayat Sigorta", "Dr. Back-Up Kişisel Sağlık Sistemi", "Ege Sigorta", "Ergo Sigorta", "Eureko Sigorta", "Grupama Emeklilik", "HDI Sigorta", "Med Power", "TBMM", "Sampo Japan Sigorta", "Şeker Sigorta", "Vakıf Emeklilik", "Ziraat Sigorta", "Zurich Sigorta" }));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setText("AGE");

        boxAge.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        boxAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxBloodGroup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxInsurance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(newUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exitFromAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(boxBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(boxInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(boxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitFromAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void newUserAddActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_newUserAddActionPerformed

    }//GEN-LAST:event_newUserAddActionPerformed


    private void exitFromAddUserMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_exitFromAddUserMouseClicked
        new Login().setVisible(true); // return to login page
        this.dispose();
    }//GEN-LAST:event_exitFromAddUserMouseClicked

    private void newUserAddMouseClicked(java.awt.event.MouseEvent evt)
    {//GEN-FIRST:event_newUserAddMouseClicked
        if (validateFields())
        {
            
            String usernameInput = tfUsername.getText();
            for (int i = 0; i < usernameInput.length(); i++) {
                if(usernameInput.charAt(i)<48 || (usernameInput.charAt(i)>57 && usernameInput.charAt(i)<65) || (usernameInput.charAt(i)>90 && usernameInput.charAt(i)<97) || (usernameInput.charAt(i)>122 && usernameInput.charAt(i)<=127)){
                    JOptionPane.showMessageDialog(AddNewUser.this, "Invalid username. Do not use special characters such as '*,+,-'");
                    return;
                }
            }
            String passwordInput = tfPassword.getText();
            String passwordControlInput = tfPassword2.getText();
            String genderInput = null;
            if (buttonFemale.isSelected()){
                genderInput = buttonFemale.getText();
            }
            else if (buttonMale.isSelected()) {
                genderInput = buttonMale.getText();
            }
            else if (buttonOther.isSelected()){
                genderInput = buttonOther.getText();
            }
            else if (buttonNotSay.isSelected()){
                genderInput = buttonNotSay.getText();
            }
            String membershipInput = null;
            ArrayList<User> users = new ArrayList<>();
            if (buttonPharmacist.isSelected()){
                membershipInput = buttonPharmacist.getText();
                users = new Pharmacist().read_txt();
            }
            if (buttonSupplier.isSelected()){
                membershipInput = buttonSupplier.getText();
                users = new Supplier().read_txt();
            }
            if (buttonCustomer.isSelected()){
                membershipInput = buttonCustomer.getText();
                users = new Customer().read_txt();
            }
            passControl();
                        
            
            
            for (int i = 0; i < users.size(); i++){
                if (users.get(i).getUsername().equals(usernameInput)){
                    JOptionPane.showMessageDialog(AddNewUser.this, "Username or ID have already taken!");
                    break;
                }
                else {
                    if(membershipInput.equalsIgnoreCase("customer")) {
                        //long id, String username, String password,String name, String surname, int age, String gender, String bloodGroup, String insurance, String membership
                        Customer newUser = new Customer(Long.parseLong(tfID.getText()), usernameInput, passwordInput, tfName.getText(), tfSurname.getText(),  Integer.parseInt(boxAge.getSelectedItem().toString()),genderInput,boxBloodGroup.getSelectedItem().toString(),boxInsurance.getSelectedItem().toString(), membershipInput);
                        User temp = (User) newUser;
                        users.add(temp);
                        new Customer().writeUsersTxt(newUser); 
                    }
                    else if(membershipInput.equalsIgnoreCase("supplier")){
                        User newUser = new Supplier(usernameInput, passwordInput, tfName.getText(), tfSurname.getText(), membershipInput);
                        users.add(newUser);
                        new Supplier().writeUsersTxt(newUser); 
                    }
                    else{
                        System.out.println("asdapsdkpoaskpodsa");
                        User newUser = new Pharmacist(usernameInput, passwordInput, membershipInput);
                        users.add(newUser);
                        new Pharmacist().writeUsersTxt(newUser);
                    }
                    
                    new Login().setVisible(true);
                    this.dispose();
                    break;
                }
            }
        }

    }//GEN-LAST:event_newUserAddMouseClicked

    private void tfSurnameActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_tfSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSurnameActionPerformed

    private void buttonFemaleActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_buttonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFemaleActionPerformed

    private void buttonMaleActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_buttonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMaleActionPerformed

    private void buttonSupplierActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_buttonSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSupplierActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void pButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseClicked
    }//GEN-LAST:event_pButtonMouseClicked

    private void pButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMousePressed
        tfPassword.setEchoChar((char)0);
        pButton.setText("Hide");
    }//GEN-LAST:event_pButtonMousePressed

    private void pButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseReleased
        tfPassword.setEchoChar('*');
        pButton.setText("Show");
    }//GEN-LAST:event_pButtonMouseReleased

    private void tfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordKeyPressed

    private void tfPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassword2KeyTyped
        tfPassword2.setEchoChar('*');
    }//GEN-LAST:event_tfPassword2KeyTyped

    private void buttonCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCustomerMouseClicked
        tfID.setEnabled(true);
        tfName.setEnabled(true);
        tfSurname.setEnabled(true);
        buttonMale.setEnabled(true);
        buttonFemale.setEnabled(true);
        buttonOther.setEnabled(true);
        buttonNotSay.setEnabled(true);
        boxBloodGroup.setEnabled(true);
        boxAge.setEnabled(true);
        boxInsurance.setEnabled(true);
    }//GEN-LAST:event_buttonCustomerMouseClicked

    private void buttonPharmacistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPharmacistMouseClicked
        tfID.setEnabled(false);
        tfName.setEnabled(false);
        tfSurname.setEnabled(false);
        buttonMale.setEnabled(false);
        buttonFemale.setEnabled(false);
        buttonOther.setEnabled(false);
        buttonNotSay.setEnabled(false);
        boxBloodGroup.setEnabled(false);
        boxAge.setEnabled(false);
        boxInsurance.setEnabled(false);
    }//GEN-LAST:event_buttonPharmacistMouseClicked

    private void buttonSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSupplierMouseClicked
        tfID.setEnabled(false);
        buttonMale.setEnabled(false);
        buttonFemale.setEnabled(false);
        buttonOther.setEnabled(false);
        buttonNotSay.setEnabled(false);
        boxBloodGroup.setEnabled(false);
        boxAge.setEnabled(false);
        boxInsurance.setEnabled(false);
        tfName.setEnabled(true);
        tfSurname.setEnabled(true);
    }//GEN-LAST:event_buttonSupplierMouseClicked

    private void tfPasswordKeyTyped(java.awt.event.KeyEvent evt) {                                      
        tfPassword.setEchoChar('*');
    }
    
    
    
    
    
    private boolean passControl()
    {
        if (!tfPassword.getText().equals(tfPassword2.getText()))
        {
            JOptionPane.showMessageDialog(AddNewUser.this, "Passwords do not match");
            tfPassword.setText("");
            tfPassword2.setText("");
            return false;
        }
        return true;
    }

    public static boolean isFullyNumeric(String string)
    {
        try {
            Long longValue = Long.parseLong(string);
            return true;
        } catch (NumberFormatException ignored) {

        }
        return false;
    }

    public boolean doesContainDigit(String string)
    {
        char[] chars = string.toCharArray();
        for(char c : chars) if (Character.isDigit(c)) return true;
        return false;
    }

    private boolean validateFields() //KONTROLLER
    {
        if(buttonCustomer.isSelected())
        {
            if(tfID.getText().length() != 11 || !isFullyNumeric(tfID.getText()) || tfID.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong ID format.");
                tfID.grabFocus();
                return false;
            }

            if (tfName.getText().isEmpty() || doesContainDigit(tfName.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong name format.");
                tfName.grabFocus();
                return false;
            }

            if (tfSurname.getText().isEmpty() || doesContainDigit(tfSurname.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong surname format.");
                tfSurname.grabFocus();
                return false;
            }

            if (tfUsername.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong username format.");
                tfUsername.grabFocus();
                return false;
            }

            if (tfPassword.getText().isEmpty() || tfPassword.getText().length() < 6)
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong password format.");
                tfPassword.grabFocus();
                return false;
            }

            if (tfPassword2.getText().isEmpty() || !tfPassword2.getText().equals(tfPassword.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Passwords do not match.");
                tfPassword2.grabFocus();
                return false;
            }

            if (!buttonMale.isSelected() && !buttonFemale.isSelected() && !buttonOther.isSelected() && !buttonNotSay.isSelected())
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Enter Any Gender.");
                buttonMale.grabFocus();
                buttonFemale.grabFocus();
                buttonOther.grabFocus();
                buttonNotSay.grabFocus();
                return false;
            }

            if(boxBloodGroup.getSelectedIndex() == 0)
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Please Select Blood Group.");
                boxBloodGroup.grabFocus();
                return false;
            }

            if(boxInsurance.getSelectedIndex() == 0)
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Please Select Insurance.");
                boxInsurance.grabFocus();
                return false;
            }

            if(boxAge.getSelectedIndex() == 0)
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Please Select Age.");
                boxAge.grabFocus();
                return false;
            }

            if (!buttonCustomer.isSelected() && !buttonPharmacist.isSelected() && !buttonSupplier.isSelected())
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Please Select Any Membership Type");
                buttonCustomer.grabFocus();
                buttonPharmacist.grabFocus();
                buttonSupplier.grabFocus();
                return false;
            }
        }
        
        else if(buttonPharmacist.isSelected())
        {
            if (tfUsername.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong username format.");
                tfUsername.grabFocus();
                return false;
            }

            if (tfPassword.getText().isEmpty() || tfPassword.getText().length() < 6)
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong password format.");
                tfPassword.grabFocus();
                return false;
            }

            if (tfPassword2.getText().isEmpty() || !tfPassword2.getText().equals(tfPassword.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Passwords do not match.");
                tfPassword2.grabFocus();
                return false;
            }
        }
        
        else if(buttonSupplier.isSelected())
        {
            if (tfName.getText().isEmpty() || doesContainDigit(tfName.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong name format.");
                tfName.grabFocus();
                return false;
            }

            if (tfSurname.getText().isEmpty() || doesContainDigit(tfSurname.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong surname format.");
                tfSurname.grabFocus();
                return false;
            }

            if (tfUsername.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong username format.");
                tfUsername.grabFocus();
                return false;
            }

            if (tfPassword.getText().isEmpty() || tfPassword.getText().length() < 6)
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Wrong password format.");
                tfPassword.grabFocus();
                return false;
            }

            if (tfPassword2.getText().isEmpty() || !tfPassword2.getText().equals(tfPassword.getText()))
            {
                JOptionPane.showMessageDialog(AddNewUser.this, "Passwords do not match.");
                tfPassword2.grabFocus();
                return false;
            }
        }
        return true;
    }

    public static void main(String[] args)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AddNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AddNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AddNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AddNewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AddNewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAge;
    private javax.swing.JComboBox<String> boxBloodGroup;
    private javax.swing.JComboBox<String> boxInsurance;
    private javax.swing.JRadioButton buttonCustomer;
    private javax.swing.JRadioButton buttonFemale;
    private javax.swing.JRadioButton buttonMale;
    private javax.swing.JRadioButton buttonNotSay;
    private javax.swing.JRadioButton buttonOther;
    private javax.swing.JRadioButton buttonPharmacist;
    private javax.swing.JRadioButton buttonSupplier;
    private javax.swing.JLabel category;
    private javax.swing.JButton exitFromAddUser;
    private javax.swing.ButtonGroup genderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newUserAdd;
    private javax.swing.JButton pButton;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JPasswordField tfPassword2;
    private javax.swing.JTextField tfSurname;
    private javax.swing.JTextField tfUsername;
    private javax.swing.ButtonGroup userButton;
    // End of variables declaration//GEN-END:variables
}
