/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ecems
 */
public class EditAccount extends javax.swing.JFrame {

    /**
     * Creates new form EditAccount
     */
    public EditAccount() {
        initComponents();
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelDefault.setVisible(true);
            panelInsurance.setVisible(false);
            panelAge.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonChangePassword = new javax.swing.JButton();
        buttonChangeInsurance = new javax.swing.JButton();
        buttonChangeUsername = new javax.swing.JButton();
        buttonChangeAge = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        panelDefault = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelUsername = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNewUsername2 = new javax.swing.JTextField();
        buttonConfirmUsername = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelCurrentUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNewUsername = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfNewPass = new javax.swing.JPasswordField();
        tfNewPass2 = new javax.swing.JPasswordField();
        pButton2 = new javax.swing.JButton();
        pButton3 = new javax.swing.JButton();
        buttonConfirmPassword = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pButton = new javax.swing.JButton();
        tfOldPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        panelInsurance = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelCurrentIns = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boxIns = new javax.swing.JComboBox<>();
        buttonIns = new javax.swing.JButton();
        panelAge = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelCurrentAge = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        boxAge = new javax.swing.JComboBox<>();
        buttonAge = new javax.swing.JButton();
        buttonGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonChangePassword.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonChangePassword.setText("Change Password");
        buttonChangePassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangePasswordActionPerformed(evt);
            }
        });

        buttonChangeInsurance.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonChangeInsurance.setText("Change Insurance");
        buttonChangeInsurance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonChangeInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeInsuranceActionPerformed(evt);
            }
        });

        buttonChangeUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonChangeUsername.setText("Change Username");
        buttonChangeUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeUsernameActionPerformed(evt);
            }
        });

        buttonChangeAge.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonChangeAge.setText("Change Age");
        buttonChangeAge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonChangeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangeAgeActionPerformed(evt);
            }
        });

        panelMain.setLayout(new javax.swing.OverlayLayout(panelMain));

        panelDefault.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/customer.png"))); // NOI18N

        javax.swing.GroupLayout panelDefaultLayout = new javax.swing.GroupLayout(panelDefault);
        panelDefault.setLayout(panelDefaultLayout);
        panelDefaultLayout.setHorizontalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefaultLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel5)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        panelDefaultLayout.setVerticalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefaultLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel5)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        panelMain.add(panelDefault);

        panelUsername.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Please confirm your new username:");

        tfNewUsername2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        buttonConfirmUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/check-double-line.png"))); // NOI18N
        buttonConfirmUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonConfirmUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonConfirmUsernameMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Current Username");

        labelCurrentUsername.setBackground(new java.awt.Color(255, 255, 255));
        labelCurrentUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelCurrentUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        labelCurrentUsername.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Please type new username:");

        tfNewUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelUsernameLayout = new javax.swing.GroupLayout(panelUsername);
        panelUsername.setLayout(panelUsernameLayout);
        panelUsernameLayout.setHorizontalGroup(
            panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsernameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsernameLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(buttonConfirmUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(tfNewUsername2)
                        .addComponent(tfNewUsername)
                        .addComponent(labelCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelUsernameLayout.setVerticalGroup(
            panelUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsernameLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNewUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonConfirmUsername)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        panelMain.add(panelUsername);

        panelPassword.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Confirm new password:");

        tfNewPass.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tfNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNewPassKeyTyped(evt);
            }
        });

        tfNewPass2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tfNewPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNewPass2KeyTyped(evt);
            }
        });

        pButton2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton2.setText("Show");
        pButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        pButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButton2MouseReleased(evt);
            }
        });

        pButton3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton3.setText("Show");
        pButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        pButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButton3MouseReleased(evt);
            }
        });

        buttonConfirmPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/check-double-line.png"))); // NOI18N
        buttonConfirmPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonConfirmPasswordMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Please write your old password");

        pButton.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton.setText("Show");
        pButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        pButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButtonMouseReleased(evt);
            }
        });

        tfOldPass.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tfOldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfOldPassKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel7.setText("New password:");

        javax.swing.GroupLayout panelPasswordLayout = new javax.swing.GroupLayout(panelPassword);
        panelPassword.setLayout(panelPasswordLayout);
        panelPasswordLayout.setHorizontalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasswordLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPasswordLayout.createSequentialGroup()
                        .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPasswordLayout.createSequentialGroup()
                                    .addComponent(tfNewPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelPasswordLayout.createSequentialGroup()
                                    .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfNewPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfOldPass, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGap(31, 31, 31)
                                    .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(79, 79, 79))
        );
        panelPasswordLayout.setVerticalGroup(
            panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasswordLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton3))
                .addGap(18, 18, 18)
                .addComponent(buttonConfirmPassword)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        panelMain.add(panelPassword);

        panelInsurance.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel8.setText("Current insurance");

        labelCurrentIns.setBackground(new java.awt.Color(255, 255, 255));
        labelCurrentIns.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelCurrentIns.setText("-");
        labelCurrentIns.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel9.setText("Please select your new insurance:");

        boxIns.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        boxIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "SGK", "Emekli Sandığı", "Ace Grup Sigorta", "Acıbadem", "Akbank", "Allianz Sigorta", "Anadolu Sigorta", "Benefit Global&Euroko Sigorta", "Demir Hayat Sigorta", "Dr. Back-Up Kişisel Sağlık Sistemi", "Ege Sigorta", "Ergo Sigorta", "Eureko Sigorta", "Grupama Emeklilik", "HDI Sigorta", "Med Power", "TBMM", "Sampo Japan Sigorta", "Şeker Sigorta", "Vakıf Emeklilik", "Ziraat Sigorta", "Zurich Sigorta" }));
        boxIns.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));

        buttonIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/check-double-line.png"))); // NOI18N
        buttonIns.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonInsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelInsuranceLayout = new javax.swing.GroupLayout(panelInsurance);
        panelInsurance.setLayout(panelInsuranceLayout);
        panelInsuranceLayout.setHorizontalGroup(
            panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsuranceLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boxIns, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelCurrentIns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInsuranceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonIns)
                .addGap(165, 165, 165))
        );
        panelInsuranceLayout.setVerticalGroup(
            panelInsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsuranceLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCurrentIns)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(boxIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(buttonIns)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        panelMain.add(panelInsurance);

        panelAge.setBackground(new java.awt.Color(255, 204, 204));

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel10.setText("Old Age");

        labelCurrentAge.setBackground(new java.awt.Color(255, 255, 255));
        labelCurrentAge.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelCurrentAge.setText("-");
        labelCurrentAge.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel12.setText("Please select your new age:");

        boxAge.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        boxAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        boxAge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));

        buttonAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/check-double-line.png"))); // NOI18N
        buttonAge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAgeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAgeLayout = new javax.swing.GroupLayout(panelAge);
        panelAge.setLayout(panelAgeLayout);
        panelAgeLayout.setHorizontalGroup(
            panelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgeLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(panelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCurrentAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxAge, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgeLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(buttonAge)
                .addGap(249, 249, 249))
        );
        panelAgeLayout.setVerticalGroup(
            panelAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgeLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(labelCurrentAge)
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(boxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(buttonAge)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        panelMain.add(panelAge);

        buttonGoBack.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/arrow-left-circle-line.png"))); // NOI18N
        buttonGoBack.setText("Go Back");
        buttonGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGoBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonChangeInsurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonChangePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonChangeUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonChangeAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonGoBack))
                .addGap(40, 40, 40)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonGoBack)
                .addGap(139, 139, 139)
                .addComponent(buttonChangeUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonChangePassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonChangeInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonChangeAge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangePasswordActionPerformed
            panelUsername.setVisible(false);
            panelPassword.setVisible(true);
            panelDefault.setVisible(false);
            panelInsurance.setVisible(false);
            panelAge.setVisible(false);
    }//GEN-LAST:event_buttonChangePasswordActionPerformed

    private void buttonChangeInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeInsuranceActionPerformed
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelDefault.setVisible(false);
            panelInsurance.setVisible(true);
            panelAge.setVisible(false);
            
            labelCurrentIns.setText(((Customer)Login.currentUser).getInsurance());
            
    }//GEN-LAST:event_buttonChangeInsuranceActionPerformed

    private void buttonChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeUsernameActionPerformed
            panelUsername.setVisible(true);
            labelCurrentUsername.setText(Login.currentUser.getUsername());
            panelPassword.setVisible(false);
            panelDefault.setVisible(false);
            panelInsurance.setVisible(false);
            panelAge.setVisible(false);
    }//GEN-LAST:event_buttonChangeUsernameActionPerformed

    private void buttonChangeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangeAgeActionPerformed
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelInsurance.setVisible(false);
            panelDefault.setVisible(false);
            panelAge.setVisible(true);
            labelCurrentAge.setText(String.valueOf(((Customer)Login.currentUser).getAge()));
    }//GEN-LAST:event_buttonChangeAgeActionPerformed

    private void buttonConfirmUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmUsernameMouseClicked
        String newUsername = tfNewUsername.getText();
        String confirmNewUsername = tfNewUsername2.getText();
        if(newUsername.equals( Login.currentUser.getUsername())){
            JOptionPane.showMessageDialog(EditAccount.this, "New and old username cannot be the same.");
        }
        
        if(!newUsername.equals(confirmNewUsername)){
            JOptionPane.showMessageDialog(EditAccount.this, "Usernames do not match.");
        }
        if(newUsername.length()<6){
            JOptionPane.showMessageDialog(EditAccount.this, "Length of new username must be equal or longer than 6.");
        }
        if(newUsername.equals(confirmNewUsername)){
            ArrayList<User> add_user= new Customer().read_txt();
            for (int i = 0; i < add_user.size(); i++) {
                if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                    add_user.get(i).setUsername(newUsername);
                    Login.currentUser.setUsername(newUsername);
                    new Customer().updateUsersTxt(add_user);
                    break;
                    }
                }
            JOptionPane.showMessageDialog(EditAccount.this, "Username has been changed.");
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelInsurance.setVisible(false);
            panelDefault.setVisible(true);
            panelAge.setVisible(false);
        }
    }//GEN-LAST:event_buttonConfirmUsernameMouseClicked

    private void tfNewPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNewPassKeyTyped
        tfNewPass.setEchoChar('*');
    }//GEN-LAST:event_tfNewPassKeyTyped

    private void tfNewPass2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNewPass2KeyTyped
        tfNewPass2.setEchoChar('*');
    }//GEN-LAST:event_tfNewPass2KeyTyped

    private void pButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton2MousePressed
        tfNewPass.setEchoChar((char)0);
        pButton2.setText("Hide");
    }//GEN-LAST:event_pButton2MousePressed

    private void pButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton2MouseReleased
        tfNewPass.setEchoChar('*');
        pButton2.setText("Show");
    }//GEN-LAST:event_pButton2MouseReleased

    private void pButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton3MousePressed
        tfNewPass2.setEchoChar((char)0);
        pButton3.setText("Hide");
    }//GEN-LAST:event_pButton3MousePressed

    private void pButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton3MouseReleased
        tfNewPass2.setEchoChar('*');
        pButton3.setText("Show");
    }//GEN-LAST:event_pButton3MouseReleased

    private void buttonConfirmPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmPasswordMouseClicked
        String oldPassword = tfOldPass.getText();
        String newPassword = tfNewPass.getText();
        String newPassword2 = tfNewPass2.getText();
        if(oldPassword.equals(newPassword)){
            JOptionPane.showMessageDialog(EditAccount.this, "New and old password cannot be the same.");
        }
        if(!newPassword2.equals(newPassword2)){
            JOptionPane.showMessageDialog(EditAccount.this, "Passwords do not match.");
        }
        else if(newPassword.length()<6){
            JOptionPane.showMessageDialog(EditAccount.this, "Size of password must be equal or longer than 6.");
        }
        else if(newPassword.equals(newPassword2)){
            
                ArrayList<User> add_user= new Customer().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        add_user.get(i).setPassword(newPassword);
                        Login.currentUser.setPassword(newPassword);
                        new Customer().updateUsersTxt(add_user);
                        break;
                    }
                }
            JOptionPane.showMessageDialog(EditAccount.this, "Password has been changed.");
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelInsurance.setVisible(false);
            panelDefault.setVisible(true);
            panelAge.setVisible(false);
        }
    }//GEN-LAST:event_buttonConfirmPasswordMouseClicked

    private void pButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMousePressed
        tfOldPass.setEchoChar((char)0);
        pButton.setText("Hide");
    }//GEN-LAST:event_pButtonMousePressed

    private void pButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseReleased
        tfOldPass.setEchoChar('*');
        pButton.setText("Show");
    }//GEN-LAST:event_pButtonMouseReleased

    private void tfOldPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOldPassKeyTyped
        tfOldPass.setEchoChar('*');
    }//GEN-LAST:event_tfOldPassKeyTyped

    private void buttonInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonInsMouseClicked
        String newIns = boxIns.getSelectedItem().toString();
        if(newIns.equals(((Customer)Login.currentUser).getInsurance())){
            JOptionPane.showMessageDialog(EditAccount.this, "New and old insurance cannot be the same.");
        }
        else{
            ArrayList<User> add_user= new Customer().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        ((Customer)Login.currentUser).setInsurance(newIns);
                        ((Customer)add_user.get(i)).setInsurance(newIns);
                        new Customer().updateUsersTxt(add_user);
                        break;
                    }
                }
            JOptionPane.showMessageDialog(EditAccount.this, "Insurance has been changed.");
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelInsurance.setVisible(false);
            panelDefault.setVisible(true);
            panelAge.setVisible(false);
        }
    }//GEN-LAST:event_buttonInsMouseClicked

    private void buttonAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAgeMouseClicked
        int newAge =Integer.valueOf( String.valueOf(boxAge.getSelectedItem()));
        if(newAge==((Customer)Login.currentUser).getAge()){
            JOptionPane.showMessageDialog(EditAccount.this, "New and old age cannot be the same.");
        }
        else{
            ArrayList<User> add_user= new Customer().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        ((Customer)Login.currentUser).setAge(newAge);
                        ((Customer)add_user.get(i)).setAge(newAge);
                        new Customer().updateUsersTxt(add_user);
                        break;
                    }
                }
            JOptionPane.showMessageDialog(EditAccount.this, "Age has been changed.");
            panelUsername.setVisible(false);
            panelPassword.setVisible(false);
            panelInsurance.setVisible(false);
            panelDefault.setVisible(true);
            panelAge.setVisible(false);
        }
    }//GEN-LAST:event_buttonAgeMouseClicked

    private void buttonGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGoBackMouseClicked
        this.dispose();
        UserStarting us = new UserStarting();
        us.setVisible(true);
    }//GEN-LAST:event_buttonGoBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAge;
    private javax.swing.JComboBox<String> boxIns;
    private javax.swing.JButton buttonAge;
    private javax.swing.JButton buttonChangeAge;
    private javax.swing.JButton buttonChangeInsurance;
    private javax.swing.JButton buttonChangePassword;
    private javax.swing.JButton buttonChangeUsername;
    private javax.swing.JButton buttonConfirmPassword;
    private javax.swing.JButton buttonConfirmUsername;
    private javax.swing.JButton buttonGoBack;
    private javax.swing.JButton buttonIns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCurrentAge;
    private javax.swing.JLabel labelCurrentIns;
    private javax.swing.JLabel labelCurrentUsername;
    private javax.swing.JButton pButton;
    private javax.swing.JButton pButton2;
    private javax.swing.JButton pButton3;
    private javax.swing.JPanel panelAge;
    private javax.swing.JPanel panelDefault;
    private javax.swing.JPanel panelInsurance;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelUsername;
    private javax.swing.JPasswordField tfNewPass;
    private javax.swing.JPasswordField tfNewPass2;
    private javax.swing.JTextField tfNewUsername;
    private javax.swing.JTextField tfNewUsername2;
    private javax.swing.JPasswordField tfOldPass;
    // End of variables declaration//GEN-END:variables
}
