/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ecems
 */
public class ManageSystem extends javax.swing.JFrame {

    /**
     * Creates new form EditAccount
     */
    DefaultTableModel table_user;
    public ManageSystem() {
        initComponents();
        panelDefault.setVisible(true);
        panelChangeUsername.setVisible(false);
        panelShowUsers.setVisible(false);
        panelChangePassword.setVisible(false);
        table_user = (DefaultTableModel) userTable.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonUsername = new javax.swing.JButton();
        buttonPassword = new javax.swing.JButton();
        buttonShowAll1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        panelDefault = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelChangeUsername = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCurrentUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNewUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNewUsername2 = new javax.swing.JTextField();
        buttonConfirmUsername = new javax.swing.JButton();
        panelShowUsers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        panelChangePassword = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pButton = new javax.swing.JButton();
        tfOldPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNewPass = new javax.swing.JPasswordField();
        tfNewPass2 = new javax.swing.JPasswordField();
        pButton2 = new javax.swing.JButton();
        pButton3 = new javax.swing.JButton();
        buttonPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonUsername.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonUsername.setText("Change Username");
        buttonUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsernameActionPerformed(evt);
            }
        });

        buttonPassword.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonPassword.setText("Change Password");
        buttonPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPasswordActionPerformed(evt);
            }
        });

        buttonShowAll1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        buttonShowAll1.setText("Show All Users");
        buttonShowAll1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonShowAll1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonShowAll1MouseClicked(evt);
            }
        });
        buttonShowAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowAll1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/arrow-left-circle-line.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(buttonUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(buttonShowAll1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(74, 74, 74)
                .addComponent(buttonUsername)
                .addGap(18, 18, 18)
                .addComponent(buttonPassword)
                .addGap(18, 18, 18)
                .addComponent(buttonShowAll1)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        panelMain.setLayout(new javax.swing.OverlayLayout(panelMain));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/pharmacy_logo.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel8.setText("EDA PHARMACY STORE");

        javax.swing.GroupLayout panelDefaultLayout = new javax.swing.GroupLayout(panelDefault);
        panelDefault.setLayout(panelDefaultLayout);
        panelDefaultLayout.setHorizontalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefaultLayout.createSequentialGroup()
                .addGroup(panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDefaultLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDefaultLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel7)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        panelDefaultLayout.setVerticalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDefaultLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        panelMain.add(panelDefault);

        panelChangeUsername.setBackground(new java.awt.Color(132, 132, 193));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Current Username");

        labelCurrentUsername.setBackground(new java.awt.Color(255, 255, 255));
        labelCurrentUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelCurrentUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        labelCurrentUsername.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Please type new username:");

        tfNewUsername.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Please confirm your new username:");

        tfNewUsername2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        buttonConfirmUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/check-double-line.png"))); // NOI18N
        buttonConfirmUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonConfirmUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonConfirmUsernameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChangeUsernameLayout = new javax.swing.GroupLayout(panelChangeUsername);
        panelChangeUsername.setLayout(panelChangeUsernameLayout);
        panelChangeUsernameLayout.setHorizontalGroup(
            panelChangeUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeUsernameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panelChangeUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChangeUsernameLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(buttonConfirmUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelChangeUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(tfNewUsername2)
                        .addComponent(tfNewUsername)
                        .addComponent(labelCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        panelChangeUsernameLayout.setVerticalGroup(
            panelChangeUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeUsernameLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNewUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonConfirmUsername)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        panelMain.add(panelChangeUsername);

        panelShowUsers.setBackground(new java.awt.Color(167, 239, 221));

        userTable.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Name", "Surname", "Age", "Gender", "Insurance", "Membership"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout panelShowUsersLayout = new javax.swing.GroupLayout(panelShowUsers);
        panelShowUsers.setLayout(panelShowUsersLayout);
        panelShowUsersLayout.setHorizontalGroup(
            panelShowUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowUsersLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        panelShowUsersLayout.setVerticalGroup(
            panelShowUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShowUsersLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        panelMain.add(panelShowUsers);

        panelChangePassword.setBackground(new java.awt.Color(132, 132, 193));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Please write your old password");

        pButton.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton.setText("Show");
        pButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        pButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButtonMouseReleased(evt);
            }
        });

        tfOldPass.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tfOldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfOldPassKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("New password:");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Confirm new password:");

        tfNewPass.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tfNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNewPassKeyTyped(evt);
            }
        });

        tfNewPass2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tfNewPass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNewPass2KeyTyped(evt);
            }
        });

        pButton2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton2.setText("Show");
        pButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        pButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButton2MouseReleased(evt);
            }
        });

        pButton3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        pButton3.setText("Show");
        pButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        pButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pButton3MouseReleased(evt);
            }
        });

        buttonPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/check-double-line.png"))); // NOI18N
        buttonPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChangePasswordLayout = new javax.swing.GroupLayout(panelChangePassword);
        panelChangePassword.setLayout(panelChangePasswordLayout);
        panelChangePasswordLayout.setHorizontalGroup(
            panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangePasswordLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelChangePasswordLayout.createSequentialGroup()
                            .addComponent(tfNewPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addComponent(pButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelChangePasswordLayout.createSequentialGroup()
                            .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNewPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfOldPass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(31, 31, 31)
                            .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(pButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(445, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangePasswordLayout.createSequentialGroup()
                .addContainerGap(450, Short.MAX_VALUE)
                .addComponent(buttonPass)
                .addGap(378, 378, 378))
        );
        panelChangePasswordLayout.setVerticalGroup(
            panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangePasswordLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton3))
                .addGap(41, 41, 41)
                .addComponent(buttonPass)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        panelMain.add(panelChangePassword);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPasswordActionPerformed
        panelChangePassword.setVisible(true);
        panelChangeUsername.setVisible(false);
        panelShowUsers.setVisible(false);
        panelDefault.setVisible(false);
    }//GEN-LAST:event_buttonPasswordActionPerformed

    private void buttonUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsernameActionPerformed
        panelShowUsers.setVisible(false);
        panelDefault.setVisible(false);
        panelChangeUsername.setVisible(true);
        labelCurrentUsername.setText(Login.currentUser.getUsername());
    }//GEN-LAST:event_buttonUsernameActionPerformed

    private void buttonConfirmUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonConfirmUsernameMouseClicked
        String newUsername = tfNewUsername.getText();
        String confirmNewUsername = tfNewUsername2.getText();
        for (int i = 0; i < newUsername.length(); i++) {
                if(newUsername.charAt(i)<48 || (newUsername.charAt(i)>57 && newUsername.charAt(i)<65) || (newUsername.charAt(i)>90 && newUsername.charAt(i)<97) || (newUsername.charAt(i)>122 && newUsername.charAt(i)<=127)){
                    JOptionPane.showMessageDialog(ManageSystem.this, "Invalid username. Do not use special characters such as '*,+,-'");
                    return;
                }
            }
        if(newUsername.equals(Login.currentUser.getUsername())){
            JOptionPane.showMessageDialog(ManageSystem.this, "New and old username cannot be the same.");
        }
        if(!newUsername.equals(confirmNewUsername)){
            JOptionPane.showMessageDialog(ManageSystem.this, "Usernames do not match.");
        }
        if(newUsername.length()<6){
            JOptionPane.showMessageDialog(ManageSystem.this, "Length of new username must be equal or longer than 6.");
        }
        if(newUsername.equals(confirmNewUsername)){
            if(Login.currentUser.getMembership().equalsIgnoreCase("Supplier")){
                ArrayList<User> add_user= new Supplier().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        add_user.get(i).setUsername(newUsername);
                        Login.currentUser.setUsername(newUsername);
                        new Supplier().updateUsersTxt(add_user);
                        break;
                    }
                }
            }
            else if(Login.currentUser.getMembership().equalsIgnoreCase("Pharmacist")){
                ArrayList<User> add_user= new Pharmacist().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        add_user.get(i).setUsername(newUsername);
                        Login.currentUser.setUsername(newUsername);
                        new Pharmacist().updateUsersTxt(add_user);
                        break;
                    }
                }
            }
            JOptionPane.showMessageDialog(ManageSystem.this, "Username has been changed."); 
            panelChangeUsername.setVisible(false);
            panelShowUsers.setVisible(false);
            panelDefault.setVisible(true);
        }
    }//GEN-LAST:event_buttonConfirmUsernameMouseClicked

    private void tfOldPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOldPassKeyTyped
        tfOldPass.setEchoChar('*');
    }//GEN-LAST:event_tfOldPassKeyTyped

    private void pButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMousePressed
        tfOldPass.setEchoChar((char)0);
        pButton.setText("Hide");
    }//GEN-LAST:event_pButtonMousePressed

    private void pButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButtonMouseReleased
        tfOldPass.setEchoChar('*');
        pButton.setText("Show");
    }//GEN-LAST:event_pButtonMouseReleased

    private void tfNewPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNewPassKeyTyped
        tfNewPass.setEchoChar('*');
    }//GEN-LAST:event_tfNewPassKeyTyped

    private void tfNewPass2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNewPass2KeyTyped
        tfNewPass2.setEchoChar('*');
    }//GEN-LAST:event_tfNewPass2KeyTyped

    private void pButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton2MousePressed
        tfNewPass.setEchoChar((char)0);
        pButton2.setText("Hide");
    }//GEN-LAST:event_pButton2MousePressed

    private void pButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton2MouseReleased
        tfNewPass.setEchoChar('*');
        pButton2.setText("Show");
    }//GEN-LAST:event_pButton2MouseReleased

    private void pButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton3MousePressed
        tfNewPass2.setEchoChar((char)0);
        pButton3.setText("Hide");
    }//GEN-LAST:event_pButton3MousePressed

    private void pButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pButton3MouseReleased
        tfNewPass2.setEchoChar('*');
        pButton3.setText("Show");
    }//GEN-LAST:event_pButton3MouseReleased

    private void buttonShowAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowAll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonShowAll1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
        ManageProduct mp = new ManageProduct();
        mp.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void buttonPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPassMouseClicked
        String oldPassword = tfOldPass.getText();
        String newPassword = tfNewPass.getText();
        String newPassword2 = tfNewPass2.getText();
        if(oldPassword.equals(newPassword)){
            JOptionPane.showMessageDialog(ManageSystem.this, "New and old password cannot be the same.");
        }
        if(!newPassword2.equals(newPassword2)){
            JOptionPane.showMessageDialog(ManageSystem.this, "Passwords do not match.");
        }
        else if(newPassword.length()<6){
            JOptionPane.showMessageDialog(ManageSystem.this, "Size of password mjst be equal or longer than 6.");
        }
        if(newPassword.equals(newPassword2)){
            if(Login.currentUser.getMembership().equalsIgnoreCase("Supplier")){
                ArrayList<User> add_user= new Supplier().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        add_user.get(i).setPassword(newPassword);
                        Login.currentUser.setPassword(newPassword);
                        new Supplier().updateUsersTxt(add_user);
                        break;
                    }
                }
            }
            else if(Login.currentUser.getMembership().equalsIgnoreCase("Pharmacist")){
                ArrayList<User> add_user= new Pharmacist().read_txt();
                for (int i = 0; i < add_user.size(); i++) {
                    if(add_user.get(i).getUsername().equals(Login.currentUser.getUsername())){
                        add_user.get(i).setPassword(newPassword);
                        Login.currentUser.setPassword(newPassword);
                        new Pharmacist().updateUsersTxt(add_user);
                        break;
                    }
                }
                
            }
            JOptionPane.showMessageDialog(ManageSystem.this, "Password has been changed.");
            panelChangePassword.setVisible(false);
            panelChangeUsername.setVisible(false);
            panelShowUsers.setVisible(false);
            panelDefault.setVisible(true);
        }
    }//GEN-LAST:event_buttonPassMouseClicked

    private void buttonShowAll1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonShowAll1MouseClicked
            if(Login.currentUser.getMembership().equalsIgnoreCase("pharmacist")){
                            panelChangePassword.setVisible(false);
            panelChangeUsername.setVisible(false);
            panelShowUsers.setVisible(true);
            panelDefault.setVisible(false);
            ArrayList<User> add_user= new Pharmacist().read_txt();
            ArrayList<User> add_user1= new Supplier().read_txt();
            ArrayList<User> add_user2= new Customer().read_txt();
            for (User user : add_user) {
                Pharmacist cs = (Pharmacist) user;
                 table_user.insertRow(userTable.getRowCount(), new Object[]{
                 "",cs.getUsername(),"","","","","",cs.getMembership()
                 });               
        }   
            for (User user : add_user1) {
                Supplier cs = (Supplier) user;
                 table_user.insertRow(userTable.getRowCount(), new Object[]{
                 "",cs.getUsername(),cs.getName(),cs.getSurname(),"","","",cs.getMembership()
                 });               
        }   
            for (User user : add_user2) {
                Customer cs = (Customer) user;
                 table_user.insertRow(userTable.getRowCount(), new Object[]{
                 cs.getId(),cs.getUsername(),cs.getName(),cs.getSurname(),cs.getAge(),cs.getGender(),cs.getInsurance(),cs.getMembership()
                 });               
        }
            }
            else{
                JOptionPane.showMessageDialog(ManageSystem.this, "You do not have permission to display this.");
            }
   
            
    }//GEN-LAST:event_buttonShowAll1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmUsername;
    private javax.swing.JButton buttonPass;
    private javax.swing.JButton buttonPassword;
    private javax.swing.JButton buttonShowAll1;
    private javax.swing.JButton buttonUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurrentUsername;
    private javax.swing.JButton pButton;
    private javax.swing.JButton pButton2;
    private javax.swing.JButton pButton3;
    private javax.swing.JPanel panelChangePassword;
    private javax.swing.JPanel panelChangeUsername;
    private javax.swing.JPanel panelDefault;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelShowUsers;
    private javax.swing.JPasswordField tfNewPass;
    private javax.swing.JPasswordField tfNewPass2;
    private javax.swing.JTextField tfNewUsername;
    private javax.swing.JTextField tfNewUsername2;
    private javax.swing.JPasswordField tfOldPass;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
