/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework;

import static homework.UserStarting.purchaseList;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ecems
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    DefaultTableModel table_cart;
    public Purchase() {
        initComponents();
        table_cart = (DefaultTableModel) tableCart.getModel();
        panelBuy.setVisible(true);
        panelCart.setVisible(true);
        panelComp.setVisible(false);
        
        fill_table();
        labelPaid.setText(String.valueOf(totalCost));
        labelWithoutD.setText(String.valueOf(costWithoutDis));
    }
    private double totalCost=0;
    private double costWithoutDis=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCart = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        labelPaid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelWithoutD = new javax.swing.JLabel();
        panelBuy = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCardNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNameSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        boxMonth = new javax.swing.JComboBox<>();
        boxYear = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tfCVC = new javax.swing.JTextField();
        buttonComplete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        boxCity = new javax.swing.JComboBox<>();
        panelComp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonHome = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        panelCart.setBackground(new java.awt.Color(10, 177, 177));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setText("Amount to be paid:");

        tableCart.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Name", "Price", "Discounted Price", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCart);

        labelPaid.setBackground(new java.awt.Color(255, 255, 255));
        labelPaid.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        labelPaid.setText("-");
        labelPaid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        labelPaid.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel8.setText("Price without discount:");

        labelWithoutD.setBackground(new java.awt.Color(255, 255, 255));
        labelWithoutD.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        labelWithoutD.setText("-");
        labelWithoutD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        labelWithoutD.setOpaque(true);

        javax.swing.GroupLayout panelCartLayout = new javax.swing.GroupLayout(panelCart);
        panelCart.setLayout(panelCartLayout);
        panelCartLayout.setHorizontalGroup(
            panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCartLayout.createSequentialGroup()
                .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCartLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(23, 23, Short.MAX_VALUE)
                        .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelWithoutD, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        panelCartLayout.setVerticalGroup(
            panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCartLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelWithoutD))
                .addGap(18, 18, 18)
                .addGroup(panelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelPaid))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        panelBuy.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Address");

        tfCardNo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfCardNo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Name-Surname");

        tfNameSurname.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfNameSurname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Expire Date");

        boxMonth.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        boxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        boxYear.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        boxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("CVC2");

        tfCVC.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfCVC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));

        buttonComplete.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonComplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/shopping-cart-2-line.png"))); // NOI18N
        buttonComplete.setText("Complete Purchase");
        buttonComplete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));
        buttonComplete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCompleteMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("Card No");

        tfAddress.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tfAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.white));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("City");

        boxCity.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        boxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "İstanbul", "Ankara", "İzmir", "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));

        javax.swing.GroupLayout panelBuyLayout = new javax.swing.GroupLayout(panelBuy);
        panelBuy.setLayout(panelBuyLayout);
        panelBuyLayout.setHorizontalGroup(
            panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuyLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNameSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(tfCardNo))
                    .addComponent(tfCVC, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuyLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfAddress))
                    .addGroup(panelBuyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonComplete))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuyLayout.createSequentialGroup()
                        .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuyLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(boxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBuyLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(boxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
        );
        panelBuyLayout.setVerticalGroup(
            panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuyLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(boxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonComplete)
                .addGap(141, 141, 141))
        );

        panelComp.setBackground(new java.awt.Color(255, 204, 204));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jLabel9.setText("PAYMENT SUCCESSFUL");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/success.png"))); // NOI18N

        buttonHome.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/home-line.png"))); // NOI18N
        buttonHome.setText("Back to Homepage");
        buttonHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonExit.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homework/close-fill-adduser.png"))); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white));
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompLayout = new javax.swing.GroupLayout(panelComp);
        panelComp.setLayout(panelCompLayout);
        panelCompLayout.setHorizontalGroup(
            panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(282, 282, 282))))
            .addGroup(panelCompLayout.createSequentialGroup()
                .addComponent(buttonHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExit)
                .addContainerGap())
        );
        panelCompLayout.setVerticalGroup(
            panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHome)
                    .addComponent(buttonExit))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCompleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCompleteMouseClicked
        if(controlInputs()){
            ArrayList<Medicament> medList = FileOperations.readMedicamentList();
            ArrayList<BabyMotherCare> momBabyList = FileOperations.getMotherBabyCareList();
            ArrayList<Dermacosmetic> dermaList = FileOperations.readDermacosmeticList();
            int i=0;
        while(i<tableCart.getRowCount()){
            if(tableCart.getValueAt(i, 4).equals("Medicament")){
                for (int j = 0; j < medList.size(); j++) {
                    if(medList.get(i).getBarcode().equals(tableCart.getValueAt(i,0))){ // get products from list
                        int oldStock = medList.get(i).getStockQ();
                        medList.get(i).setStockQ(oldStock-1); // decrease the stock beacuse it has been purchased
                        FileOperations.updateMedicamentTxt(medList); // update the txt
                        break;
                    }
                }
            }
            else if(tableCart.getValueAt(i, 4).equals("Mother And Baby Care")){
                for (int j = 0; j < momBabyList.size(); j++) {
                    if(momBabyList.get(i).getBarcode().equals(tableCart.getValueAt(i,0))){
                        int oldStock = momBabyList.get(i).getStockQ();
                        momBabyList.get(i).setStockQ(oldStock-1); // decrease the stock beacuse it has been purchased
                        FileOperations.updateMomBabyTxt(momBabyList); // update the txt
                        break;
                    }
                }
            }
            else{ // Dermacosmetic
                for (int j = 0; j < dermaList.size(); j++) {
                    if(dermaList.get(i).getBarcode().equals(tableCart.getValueAt(i,0))){
                        int oldStock = dermaList.get(i).getStockQ();
                        dermaList.get(i).setStockQ(oldStock-1); // decrease the stock beacuse it has been purchased
                        FileOperations.updateDermacosmeticTxt(dermaList); // update the txt
                        
                        break;
                    }
                }
            }
              
            
            i++;
        }
           //close unneccesary panels
          panelBuy.setVisible(false);
          panelCart.setVisible(false);
          panelComp.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_buttonCompleteMouseClicked

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        this.dispose();
        UserStarting us = new UserStarting();
        us.setVisible(true);
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
       this.dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    public void fill_table(){ // write dermacosmetic table
        int i=-1;
        for (Product product : UserStarting.purchaseList) {
                 double cost=calculateDisPrice(product.getPrice());
                 totalCost+=cost;
                 i++;
                 costWithoutDis+=product.getPrice();
                 table_cart.insertRow(table_cart.getRowCount(), new Object[]{
                     
                 product.getBarcode(),product.getProductName(),product.getPrice(),String.valueOf(cost),UserStarting.typeList.get(i)
            }); 
        }
    }
    private double calculateDisPrice(double price){
        HashMap<String,Integer> hm = FileOperations.readInsurance();
        int dis = hm.get(((Customer)Login.currentUser).getInsurance());
        double newprice = (double)(price * (100-dis)/100);
        return newprice; 
    }
    private boolean controlInputs(){ // input controls
        if(tfAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(Purchase.this, "Please Type Your Address.");
            return false;
        }
        else if(boxCity.getSelectedItem().equals("-")){
            JOptionPane.showMessageDialog(Purchase.this, "Please Select City.");
            return false;
        }
        else if(tfCardNo.getText().length()!=16){
            JOptionPane.showMessageDialog(Purchase.this, "Invalid Card No");
            return false;
        }
        else if(tfCardNo.getText().length()==16){
            for (int i = 0; i < tfCardNo.getText().length(); i++) {
                if(tfCardNo.getText().charAt(i) <48 || tfCardNo.getText().charAt(i)>57){
                    JOptionPane.showMessageDialog(Purchase.this, "Invalid Card No");
                    return false;
                }
            }
        }
        else if(tfNameSurname.getText().isEmpty()){
            JOptionPane.showMessageDialog(Purchase.this, "Please Type Name on Card.");
            return false;
        }
        else if(boxMonth.getSelectedItem().equals("-") || boxYear.getSelectedItem().equals("-")){
            JOptionPane.showMessageDialog(Purchase.this, "Invalid Expire Date.");
            return false;
        }
        else if(tfCVC.getText().length()!=3){
            JOptionPane.showMessageDialog(Purchase.this, "Invalid CVC2 No.");
            return false;
        }
        for (int i = 0; i < tfCVC.getText().length(); i++) {
            if(tfCVC.getText().charAt(i)<48 || tfCVC.getText().charAt(i)>57){
                JOptionPane.showMessageDialog(Purchase.this, "Invalid CVC2 No.");
                return false;
            }
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCity;
    private javax.swing.JComboBox<String> boxMonth;
    private javax.swing.JComboBox<String> boxYear;
    private javax.swing.JButton buttonComplete;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPaid;
    private javax.swing.JLabel labelWithoutD;
    private javax.swing.JPanel panelBuy;
    private javax.swing.JPanel panelCart;
    private javax.swing.JPanel panelComp;
    private javax.swing.JTable tableCart;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCVC;
    private javax.swing.JTextField tfCardNo;
    private javax.swing.JTextField tfNameSurname;
    // End of variables declaration//GEN-END:variables
}
